.TH bettypy 1 "12 April 2025" "BettyPy v1.0" "Man page for bettypy"
.SH NAME
bettypy \- Python style checker for Betty
.SH SYNOPSIS
.B bettypy
.I python_file
.SH DESCRIPTION
BettyPy is a Python style checker tool based on Betty's style rules.
.SH OPTIONS
No specific options are required. Simply provide the path to the Python file to analyze.
.SH EXAMPLES
Usage example:
.PP
.B bettypy
.I example.py
.SH AUTHORS
Martin Clement \- https://github.com/ItsZmainDev